In [2]:
# !pip install numpy

import numpy as np
import time

In [28]:
def time_it(func):
    # time_taken = 0
    def wrapper(*args):
        start_t=time.time()
        func(*args)
        end_t=time.time()
        time_taken=end_t-start_t
        print(f"Time Taken : {time_taken}")
    return wrapper

In [47]:
@time_it
def pythonAdd():
    a = list(range(10000))
    b = list(range(10000))
    a = [x+y for x,y in zip(a,b)]


In [48]:
time_taken_p = pythonAdd()

Time Taken : 0.005822420120239258


In [31]:
def time_it(func):
    # time_taken = 0
    def wrapper(*args):
        start_t=time.time()
        func(*args)
        end_t=time.time()
        time_taken=end_t-start_t
        print(f"Time Taken : {time_taken}")
    return wrapper

In [54]:
@time_it
def numpyAdd(a,b):
    a = np.array(a)
    b = np.array(b)
    a + b


In [55]:
a = list(range(10000))
b = list(range(10000))


In [56]:
time_taken_n = numpyAdd(a,b)

Time Taken : 0.007546424865722656


In [58]:
# time_taken_p/time_taken_n

## 1. np.array()

In [60]:
array_n1 =np.array([1,2,3,5,46])
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[ 1  2  3  5 46]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [61]:
array_n2 =np.array([1,2,3,5,46],dtype=np.int8)
print(type(array_n2))
print(type(array_n2[0]))

<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [65]:
array_n3 =np.array([1,2,3,5,"Hello",46])
print(type(array_n3))
print(type(array_n3[0]))

<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [68]:
array_n3 =np.array([1,2,3,5,"3",46],dtype=np.float16)
print(array_n3)
print(type(array_n3))
print(type(array_n3[0]))

[ 1.  2.  3.  5.  3. 46.]
<class 'numpy.ndarray'>
<class 'numpy.float16'>


## 2. np.arrange(start, stop, step)

In [69]:
print(np.arange(5))

[0 1 2 3 4]


In [70]:
print(np.arange(1,10,2))

[1 3 5 7 9]


## 3. np.linspace(start, stop, num=x)

In [72]:
# 1-2

np_linspace = np.linspace(1,1,10)
print(np_linspace)
print(type(np_linspace))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


## 4. np.zeros(shape)

In [73]:
npz_1 = np.zeros(5)

In [74]:
npz_1.ndim

1

In [75]:
npz_2 = np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [76]:
npz_3 = np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
