### Numpy Math Operation

In [ ]:
a = [1,2,3]
b = [4,5,6]

a+b    # ----> appending 

[1, 2, 3, 4, 5, 6]

#### Indexing 

In [ ]:

a[0]+b[0]

## a[0] = 1 + b[0] = 4 -> 5

5

In [4]:
import numpy as np

In [7]:
### Numpy do vectorized addition 

a = np.array([1,2,3])
b = np.array([4,5,6])

a + b

array([5, 7, 9])

In [11]:
print(type(a + b))

<class 'numpy.ndarray'>


In [8]:
## __add__
## in python we are using this  +  then it do vectorized operation

#### Simple Operators

In [10]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


####    Comparision

In [23]:
## a greater than b 
print(" a greater than b  :",a>b)
## b greater than a 
print(" b greater than a  :",a<b)
## a equal to  b 
print(" a equal to  b  :",a == b)

 a greater than b  : [False False False]
 b greater than a  : [ True  True  True]
 a equal to  b  : [False False False]


In [16]:
ans  = a + b
print(type(ans[0]))
ans  = a < b
print(type(ans[0]))

<class 'numpy.int64'>
<class 'numpy.bool'>


#### Logical Operators

In [20]:
x = np.array([True, False, True])
y = np.array([False, False, True])

In [ ]:
# And 
print(" AND :",np.logical_and(x , y))
# OR
print(" OR :",np.logical_or(x , y))
# Not
print(" NOT :",np.logical_not(x ))
# XOR
print(" XOR :",np.logical_xor(x , y))

 AND : [False False False]
 OR : [ True  True  True]
 NOT : [False  True False]
 XOR : [ True  True  True]


#### Bitwise Operators

In [26]:
a = np.array([1,2,3])
b = np.array([0,1,1]) 

In [29]:
## AND
print(" AND :",np.bitwise_and(x , y))
## OR
print(" AND :",np.bitwise_or(x , y))
## NOT
print(" AND :",np.bitwise_not(x ))
## XOR
print(" AND :",np.bitwise_xor(x , y))

 AND : [False False False]
 AND : [ True  True  True]
 AND : [False  True False]
 AND : [ True  True  True]


#### Modulus and Power

In [30]:
a = np.array([10,20,30])
b = np.array([3,7,4])

In [32]:
print("Moduls: ",np.mod(a,b))
print("Power: ",np.power(a,b))

Moduls:  [1 6 2]
Power:  [      1000 1280000000     810000]


#### Remainder and DivMod

In [33]:
a = np.array([2,4,2])
b = np.array([3,7,4])

In [34]:
print("Remainder: ",np.remainder(a,b))
print("Divmod: ",np.divmod(a,b))

Remainder:  [2 4 2]
Divmod:  (array([0, 0, 0]), array([2, 4, 2]))


#### Floor Division

In [35]:
print("Floor Division: ",np.floor_divide(a,b))

Floor Division:  [0 0 0]


Scalar Operation

In [40]:
celcius  = np.array([0,10,20,30])


In [42]:
## Broadcasting  to_farenhiet = np.array([33.8, 33.8, 33.8, 33.8])
print(celcius * 9 / 5 +32)  

[32. 50. 68. 86.]


In [48]:
# # # In python
# celcius = [0,10,20,30]
# fahrenheit = (celcius * ((9 / 5) + 32))
# print(fahrenheit)

# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[47], line 3
#       1 # # # In python
#       2 celcius = [0,10,20,30]
# ----> 3 fahrenheit = (celcius * ((9 / 5) + 32))
#       4 print(fahrenheit)

# TypeError: can't multiply sequence by non-int of type 'float'


#### Common Math Functions 

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print("Square root Value: ",np.sqrt(a))
 
print("Exponential Value: ",np.exp(a))  # e ^1 , e^2 where  e =2.718 , pi =3.14  

print("Logrithmic Value: ",np.log(a))

print("Sin Value: ",np.sin(a))

Square root Value:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
Exponential Value:  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
Logrithmic Value:  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
Sin Value:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]


In [55]:
## Machine Learning 
## Activation Function 

## sigmoid
x = np.array([-1, 0, 1])
sigmoid = 1 / (1 + np.exp(x))
print(sigmoid)

[0.73105858 0.5        0.26894142]


#### Aggregation Function 

In [56]:
a = np.array([[1,2,3],[4,5,6]])

In [62]:
print("Sum: ",np.sum(a))


Sum:  21


In [63]:
print("Sum: ",np.sum(a,axis= 0))  ##arcoss all rows fixing the coulmns 

Sum:  [5 7 9]


In [ ]:
print("Average: ",np.mean(a))  ## average

Average:  3.5


In [67]:
print("Standard Deviation: ",np.std(a))
print("Min: ",np.min(a))
print("Max: ",np.max(a))

Standard Deviation:  1.707825127659933
Min:  1
Max:  6


#### Matrix Operation  

In [69]:
units = np.array([100,200,300])
profits = np.array([10,20,30])

## element -wise multiplication
units * profits

array([1000, 4000, 9000])

In [82]:
## Matrix Multiplication OR Dot Product
# Rule are column of first matrix == rows of the second matrix
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# Location  1 G , 0 B

print("Matrix Multiplication: ",np.dot(a,b))

Matrix Multiplication:  [[19 22]
 [43 50]]


In [85]:
house = np.array([[1200, 3, 1],
                 [1200,3,0],
                 [1000,3,0],
                 [1000,1,1]])

In [86]:
w = np.array([200,1000, 50000])

In [87]:
print(house.shape)
print(w.shape)

(4, 3)
(3,)


In [88]:
print("Element wise price: ",house * w)
print("Dot product price: ",np.dot(house,w))  ## as well as do the sum as well 


Element wise price:  [[240000   3000  50000]
 [240000   3000      0]
 [200000   3000      0]
 [200000   1000  50000]]
Dot product price:  [293000 243000 203000 251000]


In [90]:
np.sum(house*w,axis=1)

array([293000, 243000, 203000, 251000])

In [91]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [92]:
print( a @ b.T)

[[17 23]
 [39 53]]


#### BroadCasting 

In [93]:
a = np.array([1,2,3])
b = np.array([[10],[20]])

In [94]:
print(a.shape)
print(b.shape)

(3,)
(2, 1)


In [97]:
a + b

# a --> (2,3)  [[1,2,3],[1,2,3]]
# b --> [[10,10,10],[20,20,20]]

array([[11, 12, 13],
       [21, 22, 23]])

#### Creating array from exisiting data

In [101]:
a = [1,2,3,4]
b = ([[1,2], [2,3]])
c = (10,20,30)

In [105]:
a_npy = np.array(a)
print(a_npy,a_npy.dtype,type(a))

[1 2 3 4] int64 <class 'list'>


In [106]:
b_npy = np.array(b)
print(b_npy,b_npy.dtype,type(b))

[[1 2]
 [2 3]] int64 <class 'list'>


In [107]:
c_npy = np.array(c)
print(c_npy,c_npy.dtype,type(c))

[10 20 30] int64 <class 'tuple'>


#### VStack

In [109]:
#vstack
a = np.array([1,2])
b = np.array([3,4])

In [110]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


#### HStack

In [111]:
print(np.hstack((a,b)))

[1 2 3 4]


#### np.char.<function_names()>

In [ ]:
# 1.np.add()

## "hello" + "hello"

a = np.array(['hello','world'])
b = np.array(['_user','_123'])

print("Char at Addition: ",np.char.add(a,b))

['hello_user' 'world_123']


In [116]:
print("Char at Addition: ",np.char.add(a,b))
print("Char at Multiplication: ",np.char.multiply(a,2))
print("Char at Modulus: ",np.char.mod(a,2))

Char at Addition:  ['hello_user' 'world_123']
Char at Multiplication:  ['hellohello' 'worldworld']
Char at Modulus:  ['hello' 'world']


In [118]:
## np.char.upper() / Lower() / capitalize()
a = np.array(['hello','WORLD'])

print("Upper : ",np.char.upper(a))
print("Lower : ",np.char.lower(a))
print("Capitalize : ",np.char.capitalize(a))

Upper :  ['HELLO' 'WORLD']
Lower :  ['hello' 'world']
Capitalize :  ['Hello' 'World']


In [119]:
## np.char.center()
print(np.char.center(a,10,fillchar='*'))

['**hello***' '**WORLD***']


#### replace()

In [121]:
a = np.array(['data_sciencce','machine_learning'])

In [122]:

print(np.char.replace(a,'_',' '))

['data sciencce' 'machine learning']


In [123]:
print(np.char.split(a,sep="_"))

[list(['data', 'sciencce']) list(['machine', 'learning'])]


In [126]:
### np.char.find()  / np.char.count()

print(np.char.find(a,'learn'))
print(np.char.count(a,"a"))

[-1  8]
[2 2]


In [127]:
#### Statistical Functions

In [128]:
data = np.array([1,2,3,4,5,6])

In [132]:
print("Mean: ", np.mean(data))
print("Median: ", np.median(data))
print("Standard Deviation: ", np.std(data))
print("Variance: ", np.var(data))
print("Min: ", np.min(data))
print("Max: ", np.max(data))

Mean:  3.5
Median:  3.5
Standard Deviation:  1.707825127659933
Variance:  2.9166666666666665
Min:  1
Max:  6


In [134]:
print("Argmin: ",np.argmin(data))
print("Argmax: ",np.argmax(data))

Argmin:  0
Argmax:  5


In [136]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
print(np.mean(matrix,axis=0))
print(np.mean(matrix,axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [ ]:
## percentile
## percentage

In [ ]:
data = np.array([1,3,5,7,9])
print(np.percentile(data,50))  ## range 1 - 100
print(np.quantile(data,0.75))  ## range 0 - 1

5.0
7.0


#### sort ,search and counting function 

In [ ]:
arr = np.array([3,4,2,1,5,7,3,2])

print("Sorted: ",np.sort(arr))
print("Sorted Indices: ",np.argsort(arr))
print("Insert 4 vlaue in which position: ",np.searchsorted(np.sort(arr),4))
print("Unique Eleement: ", np.unique(arr))
print("Count of each element: ",np.bincount(arr))

## min - 1
## max - 7
## create an array from 0 to maxelement (7) 
## 0, 1, 2, 3, 4, 5, 6 ,7  --> len(8)


Sorted:  [1 2 2 3 3 4 5 7]
Sorted Indices:  [3 2 7 0 6 1 4 5]
Insert 4 vlaue in which position:  5
Unique Eleement:  [1 2 3 4 5 7]
Count of each element:  [0 1 2 2 1 1 0 1]


In [144]:
arr = np.array([1,2,3,4])
for x in arr:
    print(x)

1
2
3
4


In [145]:
arr_2d = np.array([[1,2,3],[3,4,5]])
for x in arr_2d:
    print(x)

[1 2 3]
[3 4 5]


In [147]:
arr =np.arange(8).reshape(2,2,2)
print(arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [148]:
for x in arr:
    print(x)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [149]:
for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7


In [150]:
a = np.array([1,2,3])

In [151]:
b = a

In [152]:
b[0] = 100
print(a)

[100   2   3]


In [156]:
a = np.array([1,2,3])

In [157]:
b = a.copy()

In [159]:
b[1] = 100
print(b)
print(a)

[  1 100   3]
[1 2 3]


In [161]:
a = np.array([1,2,3])

b = a.view()

c = a.copy()

In [165]:
b[0] = 0
print(b)
print(a)

[0 2 3]
[0 2 3]


In [164]:
c[0] = 4
print(c)
print(a)

[4 2 3]
[0 2 3]


In [166]:
a = np.arange(5)
b = a[1:4] # View
print(np.shares_memory(a,b))

True


In [167]:
a = np.arange(5)
b = a[1:4].copy() 
print(np.shares_memory(a,b))

False
