In [2]:
### np.zeros()

import numpy as np

## 1. np.zeros()

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.zeros((5,5)).ndim

2

## 2. np.ones()

In [ ]:
np.ones(5)

#array([1., 1., 1., 1., 1.])-> . means  float 

array([1., 1., 1., 1., 1.])

In [7]:
np.ones((5,5),dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

## 3. np.full()

In [10]:
# list of size 10, all filled with a value 5
## np.full(Shape of the array, value that we want to assign)

In [11]:
np.full((10),5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
'''
1D --> array --> vector
2D --> array --> matrix
3D --> array --> matrix 3D
>3D --> ND array

Identity Matrix

2D, Diagonal - 1 -> Linear Algebra

'''

## 4. np.eye(n)

In [ ]:
## np.eye(no of rows)
## np.eye(no of rows, no of columns)
## np.eye(no of rows, no of columns, starting index of diagonal element )

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(3,6,-2)  #---> Create  a identity matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [17]:
np.eye(4,6,2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
## by default it is in float 

## 5. np.empty()

In [38]:
## np.empty(shape)

## it is creating a array with the default value which is garbage value

In [27]:
a = np.full((4,2),1)

In [ ]:
## I want to create a numpy array of shape 100X100X3-> 3D
# result

In [24]:
np.empty(4)

array([1., 1., 1., 1.])

In [29]:
np.empty((5,5),dtype=np.int8)  ## garbage value

array([[  0,   0,   0,   0,   0],
       [  0,   0,   0, 112, -35],
       [  5,  75, -29,   1,   0],
       [  0, -96, -33,   5,  75],
       [-29,   1,   0,   0,  16]], dtype=int8)

### time counter 

In [32]:
import time 

start_e = time.time()
np.empty((5,5))
end_e = time.time()
total_e = end_e - start_e
print(total_e)

0.0


### performance Counter

In [33]:
import time 

start_e = time.perf_counter()
np.empty((5,5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)

0.00013159999798517674


In [ ]:
import time

start_o = time.perf_counter()
np.ones((5,5))
end_o = time.perf_counter()
total_o = end_o - start_o
print(total_o)

0.00017350001144222915


In [39]:
total_o/total_e

0.9348060874988778

## 6. np.random.rand(shape)

In [42]:
np.random.rand(5,5)

array([[0.06613221, 0.18988837, 0.62828417, 0.28913051, 0.82769895],
       [0.16401237, 0.6169299 , 0.81769571, 0.70238109, 0.68164977],
       [0.2144725 , 0.52557351, 0.11809484, 0.57130424, 0.94876731],
       [0.2497891 , 0.75289575, 0.42092247, 0.7370384 , 0.38071847],
       [0.64029466, 0.67471769, 0.03322282, 0.85361839, 0.86866584]])

In [44]:
a = np.random.rand(10)*100


In [45]:
print(a)

[ 0.25700203  4.55201305 58.35294234 42.50071595 37.569773   78.99088564
 52.10233349  4.21005648 90.85470689 32.90763088]


In [47]:
a = a.tolist()

In [49]:
a  =  [int(i) for i in a]

In [50]:
print(a)

[0, 4, 58, 42, 37, 78, 52, 4, 90, 32]


## 7. np.random.randint(shape)

In [55]:
np.random.randint((4,4))

array([3, 3], dtype=int32)

In [ ]:
np.random.randint(1,11,10)
# np.random.randint(range of )

array([ 6,  5, 10,  9,  9,  3,  5, 10,  6,  7], dtype=int32)

### 8. Assignments




In [ ]:
# Assgnments 1
# a 1D array of number from 0 to 9

arr1 =np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Assignment 2
# A 3 X 3 matrix of all 5s

arr2 = np.full((3,3),5)
print(arr2)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [63]:
# Assignment 3
# A 4 X 4 identity matrix
arr3 = np.eye(4)
print(arr3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Assignment 4
# 10 evenly spaced numbers between 1 to 100

arr4 = np.linspace(1,100,10)
print(arr4)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [66]:
# Assignment 5
# A 2 X 2 array with random values between 0 to 1

arr5 = np.random.rand(2,2)
print(arr5)


[[0.96222334 0.68922905]
 [0.54546751 0.71165084]]


## 9. Numpy Attributes 

In [68]:
arr = np.array([[1,2,4],[3,5,6]])
print(arr)

[[1 2 4]
 [3 5 6]]


In [70]:
arr.shape

(2, 3)

In [71]:
arr.ndim

2

In [72]:
arr.dtype

dtype('int64')

## 10. ndarray.itemsize --> inside numpy 

In [75]:
arr.itemsize  ## no of bytes of single item.

8

In [76]:
# 1 gb --> 1024 mb 
# 1 mb --> 1024 kb
# 1 kb --> 1024 bytes
# 1 byte --> 8 bits

In [77]:
arr.nbytes # total number of bytes in array

48

In [78]:
arr = np.array([[1,2,4],[3,5,6]])

In [80]:
arr.T  ## Transpose 

array([[1, 3],
       [2, 5],
       [4, 6]])

## 11. Indexing and Slicing 

In [82]:
arr = np.array([10,20,30,40,50,60])

In [85]:
print(arr[0])

10


In [86]:
print(arr[-1])

60


In [87]:
print(arr[1:4])

[20 30 40]


In [94]:
print(arr[1:4:2])  # start with 1 and step size is 2

[20 40]


In [103]:
print(arr[::2])

[10 30 50]


In [98]:
mat  = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [101]:
print(mat[0][1])

2


In [104]:
print(mat[1])

[4 5 6]


In [105]:
print(mat[:,2])

[3 6 9]


In [110]:
print(mat[:,-1])  ## arr[no of rows,no of columns]

[3 6 9]


In [108]:
arr_temp = np.array([1,2,3,4,5,6,7,8,9])

In [109]:
arr_temp[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [132]:
mat  = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [135]:
## [[9,8,7],
## [6,5,4],
## [3,2,1]]

arr1 = mat[::-1,::-1]  ## order change 
print(arr1)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [107]:
print(mat[0:2,1:])

[[2 3]
 [5 6]]


In [136]:
arr = np.array([5,10,15,20,25])

In [137]:
arr > 10

array([False, False,  True,  True,  True])

### 12 .boolean indexing 

In [ ]:
print(arr[arr>10])  ## boolean indexing

[15 20 25]


### 13. Indexing with np.where()

In [139]:
arr = np.array([5,10,15,20,25,30])

In [140]:
idx  = np.where(arr>20)
print(idx)

(array([4, 5]),)


In [141]:
print(arr[idx])

[25 30]


## 14. Array Reshaping and Resizing 

In [142]:
aarr = np.array([5,10,15,20,25])

In [144]:
arr.shape

(6,)

In [146]:
reshape_arr = arr.reshape(2,3)

In [147]:
print(reshape_arr)

[[ 5 10 15]
 [20 25 30]]


In [153]:
arr = np.array([5,10,15,20,25,30,35,40,45,50,55,60])

In [154]:
reshapeArr = arr.reshape(3,-1)

In [155]:
print(reshapeArr)

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


In [158]:
a = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60]])

In [159]:
b = a.flatten()

In [160]:
print(b)

[ 5 10 15 20 25 30 35 40 45 50 55 60]


In [179]:
a = np.array([5,10,15,20,25,30])

In [180]:
a.resize((2,3))

In [181]:
print(a)

[[ 5 10 15]
 [20 25 30]]


In [182]:
a.resize((3,3))

In [183]:
print(a)

[[ 5 10 15]
 [20 25 30]
 [ 0  0  0]]


In [184]:
## reshape will throw error if a value are insufficient 
## resize will truncate or padd with zeros 

In [187]:
a = np.array([[[1],[2],[3]],[[1],[2],[3]]])
print(a.shape)

(2, 3, 1)


In [190]:
a = np.array([[[1],[2],[3]]])
print(a.shape)

(1, 3, 1)


In [191]:
b = np.squeeze(a)

In [192]:
print(b.shape,b)

(3,) [1 2 3]


In [193]:
b = np.array([b])
print(b)

[[1 2 3]]


In [195]:
a = np.array([[[1],[2],[3]],[[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a)
print()
print(b.shape)
print(b)

(2, 3, 1)

(2, 3)
[[1 2 3]
 [1 2 3]]


In [ ]:
# a.shape prints (2, 3, 1)
# So:

# Axis 0: size 2
# Axis 1: size 3 ← not squeezable
# Axis 2: size 1 ← squeezable

In [200]:
a = np.array([[[1],[2],[3]],[[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a,axis=2)
print()
print(b.shape)
print(b)

(2, 3, 1)

(2, 3)
[[1 2 3]
 [1 2 3]]


In [ ]:
# It gives you control over which dimension to apply a function, like sum, mean, squeeze, etc.

# Visual:

# For a 2D array:
# axis=0 → down the rows
# axis=1 → across the columns

In [206]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [207]:
print(a.shape," \n",a)

(3, 3)  
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
print(np.sum(a,axis=0))  ## row wise  1 + 1 + 1 = 3

[3 6 9]


In [ ]:
print(np.sum(a,axis=1))  ## column wise it works 1 + 2 + 3

[6 6 6]
